import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white selection:bg-white/10 font-sans">
      <div className="max-w-2xl mx-auto px-6 py-24 sm:py-32">
        <Link href="/" className="text-xs text-white/40 hover:text-white uppercase tracking-widest transition-colors mb-16 inline-block">
          ← Back
        </Link>
        
        <h1 className="text-3xl font-light mb-12 tracking-wide">Terms of Service</h1>
        
        <div className="space-y-12 text-sm">
          <section>
            <h2 className="text-white/60 uppercase tracking-widest text-xs mb-4">Acceptance</h2>
            <p className="text-white/40 leading-relaxed">
              By accessing SERVE, you agree to these Terms. If you do not agree with them, do not use the application. We built this tool to explore conversations differently. Use it responsibly.
            </p>
          </section>

          <section>
            <h2 className="text-white/60 uppercase tracking-widest text-xs mb-4">Requirements</h2>
            <p className="text-white/40 leading-relaxed mb-4">
              To use the full capabilities of SERVE, you must:
            </p>
            <ul className="list-disc pl-5 space-y-2 text-white/40 leading-relaxed">
              <li>Possess an active, valid GitHub Copilot subscription.</li>
              <li>Comply with GitHub's Acceptable Use Policies.</li>
              <li>Not attempt to exploit, reverse engineer, or abuse the API proxies provided.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white/60 uppercase tracking-widest text-xs mb-4">Liability</h2>
            <p className="text-white/40 leading-relaxed">
              SERVE is an interface for exploring AI interaction. We do not guarantee the accuracy, reliability, or safety of the responses generated by the underlying LLMs. You are solely responsible for how you interpret and use the outputs. SERVE is provided "as is" without warranty of any kind.
            </p>
          </section>
          
          <section>
            <h2 className="text-white/60 uppercase tracking-widest text-xs mb-4">Data Loss</h2>
            <p className="text-white/40 leading-relaxed">
              Because SERVE stores all logic, memory, and contexts locally in your browser's IndexedDB, we cannot recover deleted conversations. It is your responsibility to export and backup conversations if they hold value to you. We are not liable for accidental data loss initiated by browser resets or cache clearance.
            </p>
          </section>

          <section>
            <h2 className="text-white/60 uppercase tracking-widest text-xs mb-4">Modifications</h2>
            <p className="text-white/40 leading-relaxed">
              We reserve the right to modify or discontinue the SERVE web proxy at any time without notice. If GitHub fundamentally changes their Copilot API mechanics, the application may cease to function.
            </p>
          </section>

          <div className="pt-12 border-t border-white/5 text-xs text-white/20">
            Last Updated: April 2026
          </div>
        </div>
      </div>
    </div>
  );
}
